
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vlad
 */
public class laba2_version_2 extends javax.swing.JFrame {

    /**
     * Creates new form laba2_version_2
     */
    public laba2_version_2() {
        initComponents();
        /*newAbonent.add("Влад");
        newAbonent.add("Игоревич");
        newAbonent.add("Бекленищев");
        newAbonent.add("Днепр");        
        abonentsCollection.put("01497345932", newAbonent);
        
        newAbonent = new ArrayList();
        newAbonent.add("Руслан");
        newAbonent.add("Ноооо");
        newAbonent.add("Печеный");
        newAbonent.add("Днепр");        
        abonentsCollection.put("1145345932", newAbonent);
        
        newAbonent = new ArrayList();
        newAbonent.add("Таня");
        newAbonent.add("Олеговна");
        newAbonent.add("Пилипенко");
        newAbonent.add("Днепр");        
        abonentsCollection.put("0097642532", newAbonent);*/
        Map<String, Abonent> h = new HashMap<String, Abonent>();
        h.put("01497345932", new Abonent(
                "Владислав", "Игоревич", "Бекленищев", "Днепр"
        ));
        abonentsCollection.add(h);
        
        h = new HashMap<String, Abonent>();
        h.put("1145345932", new Abonent(
                "Руслан", "Ноооо", "Печеный", "Днепр"
        ));
        abonentsCollection.add(h);
        
        h = new HashMap<String, Abonent>();
        h.put("0097642532", new Abonent(
                "Таня", "Олеговна", "Пилипенко", "Днепр"
        ));
        abonentsCollection.add(h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jButtonSort = new javax.swing.JButton();
        jButtonFirst = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldMiddlename = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOut = new javax.swing.JTable();
        jButtonNextItem = new javax.swing.JButton();
        jButtonPrevItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab 2. Beklenyshchev Vladislav. PK-12-2. DNU. 2016");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonAdd.setText("Добавить");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSort.setText("Сортировать");
        jButtonSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortActionPerformed(evt);
            }
        });

        jButtonFirst.setText("Первый элемент");
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Панель для ввода"));

        jLabel3.setText("Фамилия:");

        jLabel4.setText("Город:");

        jLabel5.setText("Телефон:");

        jLabel1.setText("Имя:");

        jLabel2.setText("Отчество:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldMiddlename, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCity)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jTableOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Имя", "Отчество", "Фамилия", "Город", "Телефон"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOut);

        jButtonNextItem.setText("Следующий элемент");
        jButtonNextItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextItemActionPerformed(evt);
            }
        });

        jButtonPrevItem.setText("Предыдущий элемент");
        jButtonPrevItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPrevItem, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNextItem, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFirst)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonSort)
                    .addComponent(jButtonFirst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNextItem)
                    .addComponent(jButtonPrevItem))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // user's data:
    private List abonentsCollection 
                    = new ArrayList();
    private String currKey = "";
    
    class Abonent{
        private String name = "";
        private String middleName = "";
        private String surName = "";
        private String city = "";
        
        Abonent(){
            
        }
        
        Abonent(String name, String middleName, String surName, String city){
            this.name = name;
            this.middleName = middleName;
            this.surName = surName;
            this.city = city;
        }
        
        public String getName(){
           return name; 
        }
        
        public String getMiddleName(){
           return middleName; 
        }
        
        public String getSurName(){
           return surName; 
        }
        
        public String getCity(){
            return city;
        }
        
        public void setName(String name){
           this.name = name;
        }
        
        public void setMiddleName(String middleName){
            this.middleName = middleName;
        }
        
        public void setSurName(String surName){
            this.surName = surName; 
        }
        
        public void setCity(String city){
            this.city = city;
        }
    }
    
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        if(jTextFieldPhone.getText().equals("") ||
                jTextFieldName.getText().equals("")||
                jTextFieldMiddlename.getText().equals("") ||
                jTextFieldSurname.getText().equals("") ||
                jTextFieldSurname.getText().equals("")
        ){
            JOptionPane.showMessageDialog(null, "Проверте корректность введённых данных."
                    + "Помните, что не должно быть пустых полей!");
        }
        else{
                Map<String, Abonent> h = new HashMap<String, Abonent>();
            h.put(jTextFieldPhone.getText(), new Abonent(
                    jTextFieldName.getText(), jTextFieldMiddlename.getText(), 
                    jTextFieldSurname.getText(), jTextFieldSurname.getText()
            ));
            abonentsCollection.add(h);
            Collections.sort(abonentsCollection, new Comparator() {
                @Override
                public int compare(Object o1, Object o2) {
                    Map<String, Abonent> e1 = (Map<String, Abonent>) o1;
                    Map<String, Abonent> e2 = (Map<String, Abonent>) o2;
                    Comparable c1 = (Comparable) e1.keySet().toArray()[0];
                    Comparable c2 = (Comparable) e2.keySet().toArray()[0];
                    return c1.compareTo(c2);
                }
            });
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    //IT WORKS!
    private void jButtonSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortActionPerformed
        // TODO add your handling code here:
        Collections.sort(abonentsCollection, new Comparator() {
            @Override
            public int compare(Object o1, Object o2) {
                Map<String, Abonent> e1 = (Map<String, Abonent>) o1;
                Map<String, Abonent> e2 = (Map<String, Abonent>) o2;
                Comparable c1 = (Comparable) e1.keySet().toArray()[0];
                Comparable c2 = (Comparable) e2.keySet().toArray()[0];
                return c1.compareTo(c2);
            }
        });
    }//GEN-LAST:event_jButtonSortActionPerformed

    //IT'S WORK
    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        // TODO add your handling code here:
        Map<String, Abonent> h = new HashMap<String, Abonent>();
        h = (Map<String, Abonent>)abonentsCollection.get(0);
        String key= (String)h.keySet().toArray()[0];
        jTableOut.setValueAt(h.get(key).getName(), 0, 0);
        jTableOut.setValueAt(h.get(key).getMiddleName(), 0, 1);
        jTableOut.setValueAt(h.get(key).getSurName(), 0, 2);
        jTableOut.setValueAt(h.get(key).getCity(), 0, 3);
        jTableOut.setValueAt(key, 0, 4);
    }//GEN-LAST:event_jButtonFirstActionPerformed

    //IT'S WORK
    private void jButtonPrevItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevItemActionPerformed
        // TODO add your handling code here:
        String currKey = (String)jTableOut.getValueAt(0, 4);
        Abonent currAbonent = new Abonent(
            (String)jTableOut.getValueAt(0, 0),
            (String)jTableOut.getValueAt(0, 1),
            (String)jTableOut.getValueAt(0, 2),
            (String)jTableOut.getValueAt(0, 3)
        ); 
        Map<String, Abonent> h = new HashMap<String, Abonent>();
        int i = 0;
        String key ="";
        for(;i < abonentsCollection.size();i++){
            h = (Map<String, Abonent>)abonentsCollection.toArray()[i];
            key = (String)h.keySet().toArray()[0];
            if(currKey == key){
                break;
            }
        }
        int index = i;
        
        if(index == 0){
            index = abonentsCollection.size() - 1;
        }
        else index = index - 1;
        try{
            h = (Map<String, Abonent>)abonentsCollection.get(index);
            key= (String)h.keySet().toArray()[0];

            jTableOut.setValueAt(h.get(key).getName(), 0, 0);
            jTableOut.setValueAt(h.get(key).getMiddleName(), 0, 1);
            jTableOut.setValueAt(h.get(key).getSurName(), 0, 2);
            jTableOut.setValueAt(h.get(key).getCity(), 0, 3);
            jTableOut.setValueAt(key, 0, 4); 
        }
        catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Проверьте корректность введённых данных!");
        }
    }//GEN-LAST:event_jButtonPrevItemActionPerformed

    // IT'S WORK!
    private void jButtonNextItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextItemActionPerformed
        // TODO add your handling code here:
        String currKey = (String)jTableOut.getValueAt(0, 4);
        Abonent currAbonent = new Abonent(
            (String)jTableOut.getValueAt(0, 0),
            (String)jTableOut.getValueAt(0, 1),
            (String)jTableOut.getValueAt(0, 2),
            (String)jTableOut.getValueAt(0, 3)
        ); 
        Map<String, Abonent> h = new HashMap<String, Abonent>();
        int i = 0;
        String key ="";
        for(;i < abonentsCollection.size();i++){
            h = (Map<String, Abonent>)abonentsCollection.toArray()[i];
            key = (String)h.keySet().toArray()[0];
            if(currKey == key){
                break;
            }
        }
        int index = i;
        
        if(index == abonentsCollection.size() - 1){
            index = 0;
        }
        else index = index + 1;
        if(key.equals(""))
            index = 0;
        try{
            h = (Map<String, Abonent>)abonentsCollection.get(index);
            key= (String)h.keySet().toArray()[0];

            jTableOut.setValueAt(h.get(key).getName(), 0, 0);
            jTableOut.setValueAt(h.get(key).getMiddleName(), 0, 1);
            jTableOut.setValueAt(h.get(key).getSurName(), 0, 2);
            jTableOut.setValueAt(h.get(key).getCity(), 0, 3);
            jTableOut.setValueAt(key, 0, 4);
        }
        catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Проверьте корректность введённых данных!");
        }
        
    }//GEN-LAST:event_jButtonNextItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laba2_version_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laba2_version_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laba2_version_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laba2_version_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laba2_version_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonNextItem;
    private javax.swing.JButton jButtonPrevItem;
    private javax.swing.JButton jButtonSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOut;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldMiddlename;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
